# vim: set ft=perl :

$uplatex = 'uplatex %O -synctex=1 -interaction=nonstopmode -file-line-error %S';
$platex = 'platex %O -synctex=1 -interaction=nonstopmode -file-line-error %S';
$latex = $uplatex;
$bibtex = 'upbibtex %O %B';
$dvipdf = 'dvipdfmx %O -o %D %S';
$pdf_mode = 3;
